### ISSUE TITLE
Error with make pdf

### ISSUE THREAD

**Issue by Siggenx** [aaren/thesis#1]
Hey, your code looks great! I have trouble to get the `make pdf` to work and have a hard time finding out what is wrong. I don't know why it creates a NoneType. I just cloned your repo and installed most of the packages in environmental.yaml.

pandoc-internal-references==0.5
pandocfilters==1.2.2

Here is the error that I get (I have tried with python 2.7 too): 

```
Traceback (most recent call last):
  File "build/latex/filters.py", line 74, in <module>
    + [raw_equations])
  File "/home/sigbjorn/anaconda3/lib/python3.4/site-packages/internalreferences.py", line 497, in toJSONFilter
    altered = pf.walk(altered, action, format, doc[0]['unMeta'])
  File "/home/sigbjorn/anaconda3/lib/python3.4/site-packages/pandocfilters.py", line 30, in walk
    array.append(walk(item, action, format, meta))
  File "/home/sigbjorn/anaconda3/lib/python3.4/site-packages/pandocfilters.py", line 23, in walk
    array.append(walk(item, action, format, meta))
  File "/home/sigbjorn/anaconda3/lib/python3.4/site-packages/pandocfilters.py", line 35, in walk
    obj[k] = walk(x[k], action, format, meta)
  File "/home/sigbjorn/anaconda3/lib/python3.4/site-packages/pandocfilters.py", line 21, in walk
    res = action(item['t'], item['c'], format, meta)
  File "/home/sigbjorn/anaconda3/lib/python3.4/site-packages/internalreferences.py", line 227, in consume_references
    self.consume_math(key, value, format, metadata)
  File "/home/sigbjorn/anaconda3/lib/python3.4/site-packages/internalreferences.py", line 276, in consume_math
    label, = re.search(r'\\label{([\w:&^]+)}', math).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
pandoc: Error running filter build/latex/filters.py
make: *** [pdf] Error 83
```

**Comment by aaren** [comment]
I think I fixed that but maybe didn't push to github. Will do next week.

Thanks for trying it out. I am actively working on this and fixing things as I go along. The environment.yaml is probably out of date.

Once it's finished I intend to split off the build specific bits to a new repo. Hopefully error messages will  improve as well. Until then consider this experimental!

**Comment by Siggenx** [comment]
Ok I see thanks!

I'm trying to include Jupyter notebooks as a writing tool to easy convert to other formats, but having a difficult time with nbconvert and jinja templates getting everything to work and in this process is your code very helpful.

**Comment by aaren** [comment]
Closing this for now as it isn't a problem for me. Again, thanks for the feedback!
